name: Deploy Dragon Warriors Frontend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:22/dragon-warriors-frontend
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
          git_push_flags: --force
